#!/bin/bash

PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin

PROGNAME=`basename $0`
PROGPATH=`echo $0 | sed -e 's,[\\/][^\\/][^\\/]*$,,'`

. $PROGPATH/utils.sh

. /etc/nagios/keystonerc_nagios

if ! keystone user-get $OS_USERNAME >/dev/null 2>&1 ; then
	keystone user-get $OS_USERNAME 2>&1
	exit $STATE_CRITICAL
fi
echo OK
exit $STATE_OK
