#!/bin/bash

PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin

PROGNAME=`basename $0`
PROGPATH=`echo $0 | sed -e 's,[\\/][^\\/][^\\/]*$,,'`

. $PROGPATH/utils.sh

if ! which openstack-status > /dev/null 2>&1; then
    which openstack-status 2>&1
    exit $STATE_CRITICAL
fi

# check for enabled services that are either dead or inactive
TEXT=$(openstack-status 2>/dev/null | grep -e dead -e inactive | grep -v 'disabled on boot')
if [[ $TEXT ]] ; then
    echo $TEXT
    exit $STATE_CRITICAL
fi
echo OK
exit $STATE_OK
