#!/bin/bash

PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin

PROGNAME=`basename $0`
PROGPATH=`echo $0 | sed -e 's,[\\/][^\\/][^\\/]*$,,'`

. $PROGPATH/utils.sh

if ! keystone user-list >/dev/null 2>&1 ; then
	keystone user-list
	exit $STATE_CRITICAL
fi
echo OK
exit $STATE_OK
